# Generated by Django 2.2.6 on 2019-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
